project:
  type: book
  output-dir: docs
  
execute: 
  warning: FALSE
  message: FALSE
  cache: true

comments:
  hypothesis: 
    theme: clean

book:
  title: "Snake River GSI"
  author: "Jeff Baldock"
  date: today
  chapters:
    - index.qmd
    - part: "Genetic stock identification"
      chapters:
      - Baseline Relatedness/BaselineRelatedness.qmd
      - Baseline Testing/BaselineDataTesting.qmd
      - Baseline Fst/BaselineFst.qmd
      - GSI Analysis/GSIAnalysis.qmd
    - part: "Landscape attributes"
      chapters:
      - Landscape Covariates/Flowline Distance/FlowlineDist.qmd
      - Landscape Covariates/Groundwater/GroundwaterIndex.qmd
      - Landscape Covariates/Barriers/Barriers.qmd
      - Landscape Covariates/Landcover/Landcover.qmd
      

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    code-fold: true
    code-tools: true
    code-overflow: wrap
    number-depth: 4
    

    code-link: true
      
  pdf:
    documentclass: scrreprt

editor: source