# Introduction

This book details the analysis and code associated with the Upper Snake River Genetic Stock Identification Project. We seek to understand the role of tributary streams for supporting the mainstem Snake River population of Yellowstone cutthroat trout (*Oncorhynchus virginalis bouvieri*) in northwest Wyoming. Our primary objectives are to (1) assess the degree to which tributary contributions to the mainstem population vary across space and time and (2) quantify the effect of tributary characteristics (distance to the mainstem, catchment size, groundwater availability, and habitat connectivity) on proportional contributions to the mainstem. We found near complete reliance of the mainstem river trout population on demographic support from tributaries, but population composition varied from upstream to downstream locations. Habitat connectivity mediated the effects of distance, catchment size, and groundwater availability tributary proportional contribution. Specifically, large tributary streams located near the Snake River contributed most to the population, with groundwater-dominated tributaries contributing disproportionately relative to their size, particularly in upstream river sections. These effects were muted for tributaries in which connectivity along the migration corridor was disrupted by either natural or anthropogenic barriers to fish movement. A post-hoc analysis revealed two scales of spatial structure in contributions (after accounting for the effects of covariates). First, there was a broad latitudinal gradient, where more southerly tributaries tended to make larger contributions than more northerly tributaries. Second, tributaries located nearer each other (over fluvial distances) tended to make more similar contributions, generally reflecting nesting within HUC-8 watersheds. The results provide insight into the role of riverscape attributes for controlling functional connectivity between tribuataries and large river habitats for migratory fishes. 

*This information is preliminary or provisional and is subject to revision. It is being provided to meet the need for timely best science. The information has not received final approval by the U.S. Geological Survey (USGS) and is provided on the condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from the authorized or unauthorized use of the information.*

Project team: Jeff Baldock, Will Rosenthal, Robert Al-Chokhachy, Matt Campbell, Katie Wagner, and Annika Walters

------------------------------------------------------------------------

<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne">

Session Information

</button>

:::: {#collapseOne .accordion-collapse .collapse}
<div>

```{r}
sessionInfo()
```

</div>
::::
